// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig, env } from 'prisma/config'

export default defineConfig({
	schema: 'src/infra/database/prisma/schema.prisma',
	migrations: {
		path: 'src/infra/database/prisma/config/migrations',
	},
	datasource: {
		url: env('DATABASE_URL'),
	},
})
